<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Release;Debug</Configurations>
        <Platforms>x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Serilog" Version="4.4.1-dev-02443" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    </ItemGroup>

</Project>
